### ISSUE TITLE
DNA parameters

### ISSUE THREAD

**Issue by vbbpinheiro** [marcom/ViennaRNA.jl#10]
Love the interface of ViennaRNA for Julia. I've just installed it and I am still testing all the functions.
For now I seem unable to run **FoldCompound** using either of the DNA parameters. All RNA parameters work. 
I've gone through the code to see if I could pick any obvious glitches but I cannot find any faults there. I looked through the ViennaRNA package and both are there so I don't fully understand why I am being pushed onto "unknown energy parameters" error.

**Comment by marcom** [comment]
Thank you for the kind words. I forgot to tag a new release after adding support for DNA parameters and updating the README. I just tagged ViennaRNA v0.8.1 and DNA parameters should work now.

I haven't used the DNA parameters much myself yet, so any testing of them is much appreciated.

Something that i haven't investigated much in detail yet is that for the `:DNA_Mathews2004` parameters, ViennaRNA outputs the following warnings when loading the parameters:

```
WARNING: stacking enthalpies not symmetric
WARNING: stacking enthalpies not symmetric
WARNING: stacking enthalpies not symmetric
WARNING: stacking enthalpies not symmetric
```

**Comment by vbbpinheiro** [comment]
As far as I have tested it, everything is working well. 
I get the same warnings you mentioned but the calculations proceed without error.
I ran a few sequences through the algorithm comparing it to the output of UNAfold. Barring some minor differences among the weaker interactions, outputs matched. So, I think all is well now.

**Comment by marcom** [comment]
Thanks for testing, please let me know if there are any other problems.
