### ISSUE TITLE
Basepair probability vector and plotting RNA structures

### ISSUE THREAD

**Issue by timoleistner** [marcom/ViennaRNA.jl#3]
Would be nice to have a function which returns the basepair probabilities as a vector so it can be used later to label visualizations with the right colors.
It seems like the RNAFold webserver does this with a perl script which isnt particularly easy to read.
This is the function I came up with:
```Julia
function bpp_vec(bppm::Matrix{Float64}, dotbracket::String)
    double_bppm = transpose(bppm) + bppm
    prob_vec = Vector{Float64}(undef, first(size(double_bppm)))
    for (i, row) in enumerate(eachrow(double_bppm))
        if dotbracket[i] in ('(', ')')
            prob_vec[i] = maximum(row)
        else
            prob_vec[i] = 1 - maximum(row)
        end
    end
    return prob_vec
end
```
I'm not 100% sure this is the correct way of extracting this information though.
I've also seen that you still have [this](https://github.com/marcom/ViennaRNA.jl/blob/58a351218bfb1dcd39a1a07b8903cf76f3bfda10/src/ViennaRNA.jl#L382) in your TODO list so I'm not sure if or how this function would work after this change.

Thanks alot for porting the ViennaRNA package to julia btw. :pray:. Very nicely done!

**Comment by marcom** [comment]
Thank you for the kind words, i am glad if the package is useful. I'm travelling right now so it will be a few days until I can have a look at this properly.

Do you have a link to the  perl script you are referring to?

When plotting a particular structure, my default assumption would be that the colouring of a base would show the probability of this base being in the state it is shown, i.e. probability of being unpaired or probability of the basepair that is shown. 

Your example function used the `maximum` over a row, which might not necessarily be the probability of the basepair that is in the supplied structure. What is the reasoning behind that?

Another thing I have seen is a vector summarising the probability of a particular base being in any base pair, which would then be a `sum` instead of a `maximum`.

**Comment by marcom** [comment]
Thanks a lot for the link and your explanation.

Some comments:

The perl script that you linked to allows to colour according to positional entropy or base-pair probability (or prob. of being unpaired) with option `-p`.

The centroid secondary structure (with respect to the base-pair distance metric) is given by choosing all base pairs with probability > 0.5.

This can be seen in the ViennaRNA code in centroid.c:
https://github.com/ViennaRNA/ViennaRNA/blob/f58f58ac6fb3e050f12e69cbbf7f0a95bc625d99/src/ViennaRNA/centroid.c#L46

So i would still argue that you want to show the probability of a base-pair when plotting the secondary structure, it's just that in the case of the centroid structure this often coincides with taking the maximum over a row in the base-pair probability matrix.

Here's a rough draft of how i think the colours are calculated:
```
function prob_of_base(bppm::Matrix, pt::Pairtable)
    n = length(pt)
    size(bppm) == (n,n) || throw(ArgumentError("size mismatch bppm and pt"))
    p = bppm + bppm'
    p_unpaired = 1 .- reshape(sum(p; dims=1), (n,))
    p_base = zeros(n)
    return [pt[i] == 0 ? p_unpaired[i] : p[i, pt[i]] for i = 1:n]
end
```

This gives the same numbers as your example, but makes more sense to me when run on structures other than the centroid:
```
fc = FoldCompound("GGGGGAAAAACCCCCC")
partfn(fc)
prob_of_base(bpp(fc), Pairtable(first(centroid(fc))))
```

Some preliminary conclusions from me:

- It's annoying when the base-pair probability matrix is upper-triangular. I still think we should avoid wasting memory, but when accessing the matrix it should behave as a symmetric matrix. So for now i will change it to store all probabilities, and later we can move to a type that doesn't waste memory, like https://github.com/diegozea/PairwiseListMatrices.jl

- Some plotting support is definitely needed, at least in the basic form as seen in the ViennaRNA server. More advanced things like in VARNA would also be nice. I have some basic plotting code using `plot_coords` lying around somewhere, adding colourisation shouldn't be too hard.

- we should have some functions like prob_of_base, positional_entropy etc

**Comment by marcom** [comment]
With `v0.5.0` you can now do:

```
s = "GGGGGAAAAACCCCCC"
w, _ = centroid(s)
c = prob_of_basepairs(s, w)
plot_structure(w; sequence=s, base_colors=c, layout_type=:simple)
```

and get:

![rna](https://user-images.githubusercontent.com/71844/166234267-fe98c4ea-0673-4252-a5ad-bbcb99ff3708.png)

Easiest to try in a Pluto notebook.

Save an image like this:

```
open("save.png", "w") do io
    show(io, MIME("image/png"), plot_structure("(((...)))"))
end
```

The structure plotting is still a bit rough around the edges and only supports PNG at the moment, but let me know how it works for you.

**Comment by timoleistner** [comment]
This looks nice and thanks a lot for implementing it.
I played around with Makie.jl a bit and wrote the following plotting function :)
```Julia
function plot_structure(sequence::AbstractString; targetdir = "2D_structure.png")
		fc = FoldCompound(sequence)
		partfn(fc)
		bppm = bpp(fc)
		pt = Pairtable(first(mfe(fc)))
		coords = plot_coords(first(mfe(fc)))
		
		colorscheme = :lightrainbow
		markersize = 100 / sqrt(length(sequence))
		println(markersize)
		positions = [(a, b) for (a, b) in zip(coords...)]
		pairs = map(x -> abs.(x), filter(x -> any(i -> i < 0, x), vcat(ViennaRNA.neighbors(fc, pt)...)))
		f = Figure()
		ax = Axis(f[1, 1])
		xlims!(round(Int, minimum(first(coords))) - 10, round(Int, maximum(first(coords))) + 10)
		ylims!(round(Int, minimum(last(coords))) - 10, round(Int, maximum(last(coords))) + 10)
		hidedecorations!(ax)
		hidespines!(ax)
		x_coords = first(coords)
		y_coords = last(coords)
		for pos in pairs
			pos_x = first(pos)
			pos_y = last(pos)
			lines!(
				[x_coords[pos_x], x_coords[pos_y]],
				[y_coords[pos_x], y_coords[pos_y]],
				color = :black,
				linestyle = :dot,
				linewidth = 1,
			)
		end
		scatterlines!(ax, coords[1], coords[2],
			markersize = markersize,
			markercolor = prob_of_basepairs(bppm, pt),
			markercolormap = colorscheme,
			markercolorrange = (0, 1), # probabilities [0, 1]
			linewidth = 3,
		)
		text!(string.(collect(sequence)),
			position = positions,
			align = (:center, :center),
			textsize = markersize / 2,
		)
		Colorbar(
			f[2, 1],
			vertical = false,
			colormap = colorscheme,
		)
		ax.aspect = DataAspect()
		save(targetdir, f)
		# f
	end
```
Its possible to save the plot as PNG or PDF.
![2D_structure](https://user-images.githubusercontent.com/38843394/166248521-7aa225cd-c4b1-4941-8292-f162d2cd96c2.png)
![2D_structure_randseq_03](https://user-images.githubusercontent.com/38843394/166248538-6f21a1fe-3907-4e8a-9411-080446bbaed9.png)

Im not yet 100% sure about the markersize scaling but I've tested it a bit with sequences in lengths of 20 - 100.
You can rewrite it accordingly to this package and use it if you want.
I just wanted to leave it here in case anyone stumbling over this finds it useful :)

**Comment by marcom** [comment]
I think this looks great! I'll have to check out Makie some more.

If you want to improve the plotting in this package i'd be happy to merge any improvements. Also moving to Makie sounds ok to me as long as i can still see the plots in a Pluto notebook :)

Longer term it might make sense to have a dedicated RNA plotting package that has the best features from RiboDraw, VARNA, R2R, etc. But i don't have a lot of time to work on this for the next few months.

**Comment by timoleistner** [comment]
You can indeed see makie plots in a Pluto notebook, thats what I'm doing too. Just outcomment the `f` at the end of my plotting function.
The examples provided above look good but looking at some other examples:
![2D_structure](https://user-images.githubusercontent.com/38843394/166428226-65d803f8-7be0-497e-a75b-ed221bf8a6ac.png)
Compared to using your function:
![save](https://user-images.githubusercontent.com/38843394/166428243-c7c1c6e4-2445-4c2b-b721-8ae74d2c49be.png)
Small loop structures are somehow skewed together and worse to see than in your visualization.
I'm not exactly sure why this is happening though as I'm using the coordinates provided by the algorithm  from ViennaRNA.
Do you somehow modify the coordinates?

**Comment by marcom** [comment]
That sounds great!

I just changed the default layout_type as i had the same problem with the naview algorithm, but it's not in a released version yet.

**Comment by marcom** [comment]
I moved the structure plotting functionality to a new package:

https://github.com/marcom/PlotRNA.jl

as it was really slowing down the load time of this package (see issue #8)
